### ISSUE TITLE
Need help to get PICA Path to work

### ISSUE THREAD

**Issue by nwagner84** [gbv/PICA-Data#132]
Hi,

in order to learn the usage and features of PICA Path expressions, I get an error in `picadata`:

```bash
$ picadata "012A[*]" -f plus DUMP.dat | pica print --add-spaces
File not found: 012A[*]
```

The expression was built from ebnf ("Standard-Erweiterungen",  access date 06.02.2023). Whats wrong with the expression? File file exists and the command also works with other PICA Path expression. I've already tried to quote the `*`, but with no success.

```bash
$ picadata --version                                              
2.06

$ perl --version                                                  

This is perl 5, version 32, subversion 1 (v5.32.1) built for x86_64-linux-gnu-thread-multi
(with 47 registered patches, see perl -V for more detail)

Copyright 1987-2021, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
```

What am I doing wrong?

**Comment by nichtich** [comment]
Path expressions are not fully detected automatically so far, so explicitly use option `-p/--path`:

   picadata -p "012A[*]" -f plus DUMP.dat | pica print --add-spaces

I'd discourage use of "`[`...`]`" in favour of "`/`..." to specify occurrence but previous applications used it. The syntax [introduced here](https://github.com/gbv/PICA-Data/issues/109#issuecomment-981562847) (not including xtags) is a compromise.
