### ISSUE TITLE
Occurrences and repeated fields

### ISSUE THREAD

**Issue by cKlee** [gbv/PICA-Data#19]
I'm a little confused about the occurrences in PICA::Data / PICA::Path. At glance I thought with occurrence you mean 'field repetition'. But actually occurrence is only derived from the enumeration of holding fields, like 

    201U/01 $0utf8 -> ['201U', '01', '0' => 'uft-8']

But in the `pica_map` POD it seems like you can use PICA::Path to filter for field repetitions:

    # Copy from field 028A with occurrence subfields a and d to dc.contributor hash joining them by ' '
    pica_map('028B[01]ad','dcterms.contributor', -join => ' ');

@nichtich @jorol

**Comment by nichtich** [comment]
Occurrences are integral part of field identifiers, they do not refer to field repetition. There might be a bug in Catmandu::Fix::pica_map, but this method is not part of PICA::Data. Should I keep the question open?

**Comment by cKlee** [comment]
No, there is no such bug in Catmandu::Fix::pica_map. But the POD is misleading. One can easily mistake occurrence for field repetition.
