### ISSUE TITLE
Add parser and writer for WinIBW download format

### ISSUE THREAD

**Issue by jorol** [gbv/PICA-Data#34]
see https://github.com/gbv/Catmandu-PICA/issues/4

**Comment by cKlee** [comment]
I see some problems here. The download format is not produced by the WinIBW but by the CBS. Thus CBS configuration must be taken into account and so there are several possibilities an download could appear. In WinIBW you can make a download in the cataloging format (PICA 3). Subfield separators (if present) can vary and the intermediate SET descriptions and headers can change by language.

    SET: S2 [38] TTL: 1           PPN: 017995043                            SEITE1 .

    Eingabe: 9001:21-11-99 Änderung: 9999:01-12-17 16:39:58 Status: 9001:26-05-05

**Comment by jorol** [comment]
We should check the PICA3 download formats of DNB, GBV, hebis and SWB and see what are common patterns and what needs to be  parameterized.

**Comment by nichtich** [comment]
See https://metacpan.org/pod/distribution/PICA-Record/bin/winibw2pica for an old script to parse/cleanup WinIBW PICA format.

**Comment by nichtich** [comment]
PICA Plain parser also support WinIBW download format starting with release 1.22.
