### ISSUE TITLE
Drop usage of * for wildcard from PICA::PATH

### ISSUE THREAD

**Issue by cKlee** [gbv/PICA-Data#47]
@nichtich @jorol 

Asterisk * as a wildcard is not common in Catmandu paths. Is there a problem by dropping it and use dots only?

I know, it's a breaking change ... Make it version 1.x then?

see https://github.com/gbv/Catmandu-PICA/issues/63

**Comment by nichtich** [comment]
I'm ok with replacing `*` with `.` for a single character.

**Comment by jorol** [comment]
Fixed in v1.00. New Catmandu::PICA release will follow.
