### ISSUE TITLE
Put specification of PICA Path into independent document

### ISSUE THREAD

**Issue by nichtich** [gbv/PICA-Data#51]
I added PICA Path to the collection of data formats and related standards at <http://format.gbv.de/query/picapath> but there is no specification to link to. Specification of PICA Path expressions should be formalized and written down in an independent document or section (e.g. `PICA::Path::Specification`) to implement against.

See <http://format.gbv.de/application/query> for more query formats.

**Comment by jorol** [comment]
The description of PICA::PATH with examples is now part of https://metacpan.org/pod/PICA::Path.
