### ISSUE TITLE
Support sorting records

### ISSUE THREAD

**Issue by nichtich** [gbv/PICA-Data#59]
Sorting [had been removed](https://github.com/gbv/PICA-Data/commit/e6a93b1fcb8d300ca938f3953350bea3db9a1876#diff-2399311de91afba3297f21cee088a08aL45-L53) because it was buggy. Add a proper implementation. Also add CLI option `--order, -o` to enable sorting

**Comment by jorol** [comment]
See also https://github.com/gbv/Catmandu-PICA/issues/69
