### ISSUE TITLE
Files with subfield indicator ƒ omit ppn from output

### ISSUE THREAD

**Issue by hemmefelix** [gbv/PICA-Data#80]
https://github.com/GBV/PICA-Data/issues/67 introduced `ƒ` as subfield indicator. Files that contain this character as subfield indicator can be parsed without any issues, but the output omits the ppn record id from 003@.

Expected result:
`<ppn>: <error message>`

Actual result:
`: <error message>`

**Comment by nichtich** [comment]
Sorry, I cannot reproduce this error. Can you give an example of an input file and command/script applied to the file?

**Comment by nichtich** [comment]
Has been fixed:

    $ printf '003@ ƒ023\n021A ƒzx' | picadata validate -s k10plus.json -u
    23: unknown subfield 021A$z
